name: Sentieon Alignment and Variant Calling for Long Read Data with Sentieon CLI
description: Perform alignment (Sentieon Minimap2) and variant calling (Sentieon CLI) for long read data
stages:
  - name: Alignment with Minimap2
    description: Align long read data with Minimap2
    task_path: "Sentieon CLI/sentieon_minimap2.task.yaml"
    depends_on: []

    glob_parameter:
      label: Input File Base Directory
      path:
        type: directory
        supports_location_mode: 'read_only'
      glob_ex: '**/*-*.bam'
      output_parameters:
        - task_parameter_name: input_file
          expression: '${file_directory}'
        - task_parameter_name: sample_name
          expression: '${2}'

    task_parameters:
      - name: output_folder
        label: Output Folder
        type: directory
        supports_location_mode: 'no_append'

      - name: tech
        label: Sequencing Technology
        type: enum
        choices: ["HiFi", "ONT"]
        value: "HiFi"

      - name: ref_fasta
        label: Reference File (FASTA)
        type: file
        optional: true
        help: Reference file to use for alignment. If not provided, the default reference file will be used.
        supports_location_mode: 'read_only'

      - name: model_base_path
        label: Sentieon Models Base Path
        type: directory
        optional: true
        help: Path to the Sentieon models base directory. If not provided, the default models will be used.
        supports_location_mode: 'read_only'

  - name: Variant Calling with Sentieon CLI
    description: Call variants with Sentieon CLI
    task_path: "Sentieon CLI/sentieon_cli_long_read.task.yaml"
    depends_on: ["Alignment with Minimap2"]

    glob_parameter:
      label: Alignment Folder
      path:
        type: stage
        stage: Alignment with Minimap2
        parameter: output_folder
      glob_ex: '**/*_minimap2.bam'
      output_parameters:
        - task_parameter_name: input_file
          expression: '${0}'
        - task_parameter_name: sample_name
          expression: '${2}'

    task_parameters:
      - name: gvcf
        label: Generate gVCF
        help: Generate a gVCF output file along with the VCF
        type: boolean
        value: "true"

      - name: skip_small_variants
        label: Skip Small Variants
        help: Skip small variant (SNV/indel) calling
        type: boolean
        value: "false"

      - name: skip_svs
        label: Skip SVs
        help: Skip structural variant calling
        type: boolean
        value: "false"

      - name: skip_mosdepth
        label: Skip Mosdepth QC
        help: Skip QC with mosdepth
        type: boolean
        value: "false"
      
      - name: tech
        label: Sequencing Technology
        type: stage
        stage: Alignment with Minimap2
        expression: '${tech}'

      - name: output_folder
        label: Output Folder
        type: stage
        stage: Alignment with Minimap2
        expression: '${output_folder}'

      - name: ref_fasta
        label: Reference File (FASTA)
        type: stage
        stage: Alignment with Minimap2
        expression: '${ref_fasta}'

      - name: model_base_path
        label: Sentieon Models Base Path
        type: stage
        stage: Alignment with Minimap2
        expression: '${model_base_path}'
